### ISSUE TITLE
Registry Based Structure Key/Part System

### ISSUE THREAD

**Issue by ticticboooomer** [ticticboooomer/MasterfulMachinery#19]
### Design

create base structure key which can be applied to all blocks with the following settings:
- block state properties
- NBT (Possibly?)

Create subclasses of the base structure key which specialise the search requirements of blocks.

Then create a Structure Key Parser which parses the key JSON objects into the respective subclass.

### Example:
```json
{
  "A": {
    "block": "mm:controller_a",
    "state_properties": [
      {
        "property": "facing",
        "value": "north"
      },
      {
        "property": "axis",
        "value": "y"
      }
    ]
  }
}
```

**Comment by WhiseNT** [comment]
I am unable to edit these in kubejs. Do you have any plans to add support for this?
