### ISSUE TITLE
[BUG] File MasterfulMachinery... is not a valid mod file

### ISSUE THREAD

**Issue by CG-Matt** [ticticboooomer/MasterfulMachinery#48]
# Version Information
Forge version:  47.2.0
Masterful Machinery version: V3-MC1.20.1-B0.1.1

ADD ON'S
Optifine version: null  
Botania version: null  
Create version: null  
Mekanism version: null  
Pneumaticcraft version: null  
Astral Sorcery version: null  

# Further Information
Link to latest.log: https://pastebin.com/eNpfX7ng
Steps to reproduce:
1. Launch Minecraft

What I expected to happen:
The mod to work

What happened instead:
The mod did not work

**Comment by ticticboooomer** [comment]
i have removed the broken file from curseforge and will upload the replacement without the versioning errors. first i need to sort a couple of issues with the file that were unrelated to the versioning

**Comment by ticticboooomer** [comment]
fixed in the latest version `3-1.20.1-0.1.1`
