### ISSUE TITLE
[BUG] Can't start server

### ISSUE THREAD

**Issue by srccc74** [ticticboooomer/MasterfulMachinery#68]
Minecraft version: 1.20.1
Forge version: 47.2.32
Mod version: 0.1.7

**Seems like it's trying to load class which is not enable on server side**

Screenshot of error:
![image](https://github.com/ticticboooomer/MasterfulMachinery/assets/78021989/c9c12dae-1a5c-4c4c-a797-8c221f9a3754)

**Comment by ticticboooomer** [comment]
please can this be discussed in our discord server as communicating is easier there. Using github creates many challenges for efficiency
 discord: https://discord.masterfulmc.com

**Comment by ticticboooomer** [comment]
closing as fix has been released and no further help sought
