### ISSUE TITLE
[BUG] Create kinetic port output keeps outputting rotation after the recipe ends

### ISSUE THREAD

**Issue by JJRobot25** [ticticboooomer/MasterfulMachinery#74]
# Version Information
Forge version:  47.2.17
Masterful Machinery version: 3-1.20.1-0.1.11

ADD ON'S
Create version: 1.20.1-0.5.1.f
Mekanism version: 10.4.8.43

# Further Information
Link to latest.log: [gist](https://gist.github.com/JJRobot25/0ad291f337986d04cca4d6fe47ddabaf)  
Steps to reproduce:
1. Make a recipe with item input and kinetic output
2. Input item

What I expected to happen:
The kinetic port output to stop rotating after the recipe ends

What happened instead:
It keeps outputting rotation

**Comment by JJRobot25** [comment]
Other mods I have installed are:
- Create Ore Excavation (1.20.1-1.4.4)
- Create: The Factory Must Grow (0.8.0b)
- EMI (1.1.7+1.20.1+forge)
- Just Enough Items (15.3.0.8)
- KubeJS (2001.6.5-build.14+forge)
- Mekanism Generators (10.4.8.43)
- Rhino (2001.2.2-build.18+forge)

I don't think they're relevant to the bug, but just in case

**Comment by ticticboooomer** [comment]
fixed in 0.1.12 in 1.20.1
