### ISSUE TITLE
[BUG] 1.20.1 JEI checking multiblocks crashes game with "Index 0 out of bounds for length 0"

### ISSUE THREAD

**Issue by Joshernoob** [ticticboooomer/MasterfulMachinery#75]
Forge version:  47.2.32
Masterful Machinery version: 0.1.11

ADD ON'S
N/A

Botania version:  444
Mekanism version: 10.4.8.43
Pneumaticcraft version: 6.0.15

Link to Log: https://gist.github.com/Joshernoob/dcf3c252ffd026f0a8bc7d8fed23c913
1. Load game with mods and multiblock
2.  load world
3. try to use u on the controller to find it use
4. crash to desktop

What I expected to happen:
should show a JEI multiblock

What happened instead:
crash to desktop with a crash report naming this mod, JEI and Fancy Menu as the problems (if that helps)

**Comment by ticticboooomer** [comment]
this is not a bug, pls create a ticket in the discord server. i can help you resolve it there
