### ISSUE TITLE
[1.19.2-BUG] Energy Port GUI Visual Issues

### ISSUE THREAD

**Issue by ticticboooomer** [ticticboooomer/MasterfulMachinery#77]
![Image](https://github.com/ticticboooomer/MasterfulMachinery/assets/115849106/4a7407a5-72f7-4519-8311-1a427bcda4db)

**Comment by HyperRaccoon13** [comment]
To re create:
set the energy port to 10,000 
fill the energy up. 
then change the energy to a lower value. 

![image](https://github.com/ticticboooomer/MasterfulMachinery/assets/68512889/bdd79cd9-4b16-412a-9dd3-7aaf42ef658b)
